# Generated by Django 5.0.1 on 2024-02-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_instrumentos_operaciones_tipos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentos',
            options={'ordering': ['tipo', 'descripcion'], 'verbose_name': 'Instrumento', 'verbose_name_plural': 'Instrumentos'},
        ),
        migrations.AlterModelOptions(
            name='operaciones',
            options={'ordering': ['fecha'], 'verbose_name': 'Operación', 'verbose_name_plural': 'Operaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipos',
            options={'ordering': ['tipo'], 'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['apellido'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RenameField(
            model_name='operaciones',
            old_name='Tipo',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='operaciones',
            name='email',
        ),
        migrations.AddField(
            model_name='operaciones',
            name='cuenta',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrumentos',
            name='descripcion',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='instrumentos',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instrumentos',
            name='tipo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='operaciones',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='operaciones',
            name='nominales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tipos',
            name='renta',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tipos',
            name='tipo',
            field=models.CharField(max_length=40),
        ),
    ]
